drop table if exists users, categories, events, compilations, compilation_events, views, requests;

create table if not exists users
(
    id    bigint  not null generated by default as identity primary key,
    name  varchar not null,
    email varchar not null unique
);

create table if not exists categories
(
    id   bigint      not null generated by default as identity primary key,
    name varchar(50) not null unique
);

create table if not exists events
(
    id                 bigint                                               not null generated by default as identity primary key,
    annotation         varchar                                              not null,
    category_id        integer references categories (id) on delete cascade not null,
    confirmed_requests integer,
    created_on         timestamp without time zone                          not null,
    description        varchar                                              not null,
    event_date         timestamp without time zone                          not null,
    initiator_id       integer references users (id) on delete cascade,
    lon                float                                                not null,
    lat                float                                                not null,
    paid               boolean                                              not null,
    participant_limit  integer                                              not null,
    published_on       timestamp without time zone,
    request_moderation boolean                                              not null,
    state              varchar                                              not null,
    title              varchar                                              not null,
    views              integer
);

create table if not exists compilations
(
    id     bigint  not null generated by default as identity primary key not null,
    title  varchar not null unique,
    pinned boolean not null
);

create table if not exists compilation_events
(
    id             bigint                                                 not null generated by default as identity primary key not null,
    event_id       integer references events (id) on delete cascade       not null,
    compilation_id integer references compilations (id) on delete cascade not null
);

create table if not exists views
(
    id       bigint                         not null generated by default as identity primary key,
    event_id integer references events (id) not null,
    ip       varchar                        not null
);

create table if not exists requests
(
    id           bigint                         not null generated by default as identity primary key,
    event_id     integer references events (id) not null,
    requester_id integer references users (id)  not null,
    status       varchar                        not null,
    created      timestamp without time zone    not null
);