drop table if exists stats;

create table if not exists stats (
    id int generated by default as identity not null primary key,
    app varchar,
    uri varchar,
    ip varchar,
    timestamp varchar
);