version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-main
    image: mamaiwyd/stats-main-image:latest
    container_name: stats-main-container
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=9090
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stats-db
    volumes:
      - ./stats-service/stats-main/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
