version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-main
    image: mamaiwyd/stats-main-image:latest
    container_name: stats-main-container
    depends_on:
      - stats-db
    environment:
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=9090
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    container_name: stats-db-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stats-db
    volumes:
      - ./stats-service/stats-main/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - stats-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  ewm-service:
    ports:
      - "8080:8080"
    build: ./main-service
    image: mamaiwyd/ewm-main-image:latest
    container_name: ewm-main-container
    depends_on:
      - ewm-db
    environment:
      - SPRING_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/main-db
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_PORT=8080
      - SERVICE_URL=http://stats-server:9090/

  ewm-db:
    image: postgres:16.1
    container_name: main-db-container
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main-db
    volumes:
      - ./main-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ewm-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

volumes:
  stats-db-data:
  ewm-db-data:
